# start: docker-compose up -d
# stop: docker-compose down

name: Saga
services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "8000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./traefik/conf/:/etc/traefik/conf/
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:17.2
    container_name: postgres-saga
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: orchestratorservice, paymentservice, inventoryservice, shippingservice
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
      - ./db/postgress/:/var/lib/postgresql/data/
    networks:
      local-network:

  kafka:
    image: apache/kafka:3.7.2
    container_name: kafka
    restart: unless-stopped
    ports:
      - 9092:9092
    # comenvironment:
    #   KAFKA_NODE_ID: 1
    #   KAFKA_PROCESS_ROLES: broker,controller
    #   KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
    #   KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    #   KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    #   KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    #   KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
    #   KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #   KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    #   KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    #   KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    #   KAFKA_NUM_PARTITIONS: 3
    networks:
      local-network:

networks:
  local-network:
    driver: bridge
