# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: orchestratorservice
services:
  app:
    image: orchestratorservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:5000/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
  consul:
    extends:
      file: ./consul.yml
      service: consul
  consul-config-loader:
    extends:
      file: ./consul.yml
      service: consul-config-loader
